# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ec51ae1527ad4cfe81da5b41e6c8a439d3468820cc310d9677a5cbf7744c555ea8896a480ea133d648a9fd4ecbbafdd6706b2be316dfc74c854efe08396154

test:
  secret_key_base: 0293ce902d461d3ce086b30dfb70d02ad8585a597fd02cb0a868f82a4be8ac69540b0ea3602c87117465f3ecbaa1c75902fabf625b9e79ce364d2de6c2f21def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
